### ISSUE TITLE
Redo is executing forever

### ISSUE THREAD

**Issue by edysegura** [AlexanderBrevig/CommandManager.js#1]
Hi @AlexanderBrevig! Testing the redo action in your command manager I noticed that it is executing forever. Is that the expected behavior?

Thank you in advancement!

**Comment by AlexanderBrevig** [comment]
Hi! Can you provide some sample code that reproduces this bug?
Are you able to reproduce it here http://alexanderbrevig.github.io/CommandManager.js/examples/ ?

Thanks for reporting it :)

**Comment by edysegura** [comment]
If I add a number and than click in undo the number will be removed, but when I click in redo more than twice it will replicate the number as much as you click in redo. 

I thought it was to redo just once.

**Comment by AlexanderBrevig** [comment]
Ah, right. Well. Per now this is a feature and not a bug. I used it so that whenever the app did something. I added it to the redo stack and as such the user could then duplicate by doing redo. Some applications work this way.

Hope it's not a problem to you. I could add a flag or something to make it change behavior.
